// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5265.Robot00;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveBaseLeftFrontMotor;
    public static SpeedController driveBaseLeftRearMotor;
    public static SpeedController driveBaseRightFrontMotor;
    public static SpeedController driveBaseRightRearMotor;
    public static RobotDrive driveBaseRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveBaseLeftFrontMotor = new Talon(0);
        LiveWindow.addActuator("DriveBase", "Left Front Motor", (Talon) driveBaseLeftFrontMotor);
        
        driveBaseLeftRearMotor = new Talon(1);
        LiveWindow.addActuator("DriveBase", "Left Rear Motor", (Talon) driveBaseLeftRearMotor);
        
        driveBaseRightFrontMotor = new Talon(2);
        LiveWindow.addActuator("DriveBase", "Right Front Motor", (Talon) driveBaseRightFrontMotor);
        
        driveBaseRightRearMotor = new Talon(3);
        LiveWindow.addActuator("DriveBase", "Right Rear Motor", (Talon) driveBaseRightRearMotor);
        
        driveBaseRobotDrive = new RobotDrive(driveBaseLeftFrontMotor, driveBaseLeftRearMotor,
              driveBaseRightFrontMotor, driveBaseRightRearMotor);
        
        driveBaseRobotDrive.setSafetyEnabled(true);
        driveBaseRobotDrive.setExpiration(0.1);
        driveBaseRobotDrive.setSensitivity(0.5);
        driveBaseRobotDrive.setMaxOutput(1.0);
        driveBaseRobotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        driveBaseRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        driveBaseRobotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveBaseRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
