// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5265.Robot01.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5265.Robot01.Robot;
import com.ni.vision.NIVision;
import com.ni.vision.NIVision.Image;

//import edu.wpi.first.wpilibj.CANSpeedJoystick;
import edu.wpi.first.wpilibj.CameraServer5265;
import edu.wpi.first.wpilibj.Config;
import edu.wpi.first.wpilibj.Joystick;

/**
 *
 */
public class SwitchCamera extends Command {

		private final int cam0;
		private final int cam1;
		private int curCam;
		private Image frame;
		private CameraServer5265 server;
		private Joystick contr;

public SwitchCamera(Joystick newContr)
		{
	        // Get camera ids by supplying camera name ex 'cam0', found on roborio web interface
	        cam0 = NIVision.IMAQdxOpenCamera(Config.SwitchCamera.camNameFront, NIVision.IMAQdxCameraControlMode.CameraControlModeController);
	        cam1 = NIVision.IMAQdxOpenCamera(Config.SwitchCamera.camNameBack, NIVision.IMAQdxCameraControlMode.CameraControlModeController);
	        curCam = cam0;
	        // Img that will contain camera img
	        frame = NIVision.imaqCreateImage(NIVision.ImageType.IMAGE_RGB, 0);
	        // Server that we'll give the img to
	        server = CameraServer5265.getInstance();
	        server.setQuality(Config.SwitchCamera.imgQuality);
	        contr = newContr;
		}

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	
	
	
    /*// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public SwitchCamera() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }*/

    // Called just before this Command runs the first time
	public void run()
	{
		if(contr.getRawButton(Config.SwitchCamera.btCamCenter))
			changeCam(cam0);
	
		if(contr.getRawButton(Config.SwitchCamera.btCamRight))
			changeCam(cam1);
	
		updateCam();
	}

    // Called repeatedly when this Command is scheduled to run
	public void end()
	{
		NIVision.IMAQdxStopAcquisition(curCam);
	}

	public void changeCam(int newId)
    {
		NIVision.IMAQdxStopAcquisition(curCam);
    	NIVision.IMAQdxConfigureGrab(newId);
    	NIVision.IMAQdxStartAcquisition(newId);
    	curCam = newId;
    }
	public void updateCam()
    {
    	NIVision.IMAQdxGrab(curCam, frame, 1);
        server.setImage(frame);
    }

	@Override
	protected void initialize() {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected void execute() {
		// TODO Auto-generated method stub
		
	}

	@Override
	protected boolean isFinished() {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	protected void interrupted() {
		// TODO Auto-generated method stub
		
	}

	
}
