// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5265.Robot01.subsystems;

import org.usfirst.frc5265.Robot01.Robot;
import org.usfirst.frc5265.Robot01.RobotMap;
import org.usfirst.frc5265.Robot01.commands.*;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveBase extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Encoder quadratureEncoder1 = RobotMap.driveBaseQuadratureEncoder1;
    private final CANTalon leftFrontMotor = RobotMap.driveBaseLeftFrontMotor;
    private final CANTalon leftRearMotor = RobotMap.driveBaseLeftRearMotor;
    private final CANTalon rightFrontMotor = RobotMap.driveBaseRightFrontMotor;
    private final CANTalon rightRearMotor = RobotMap.driveBaseRightRearMotor;
    private final RobotDrive robotDrive = RobotMap.driveBaseRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new GoArcade());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
   
    
    public void GoArcade(Joystick stick) {
    	robotDrive.arcadeDrive(stick);    	
	}
    
    public void GoForward(double speed) {
    	robotDrive.tankDrive(speed, speed);
    }
    
    public void GoBackward(double speed) {
    	robotDrive.tankDrive(-speed, -speed);
    }
    
    public void GoDrive(double speedLeft, double speedRight) {
    	robotDrive.tankDrive(speedLeft, speedRight);
    }
    
    public void GoStop(double speed) {
    	robotDrive.tankDrive(0, 0);
    }
    
    public void drive(double left, double right) {
		robotDrive.tankDrive(left, right);
		//Robot.driveBase.tankDrive(left, right);
	}
public double FindThrottle(double speedValue){
    	Robot.driveBase.GoBackward(speedValue);
    	return speedValue;
    }
    
   
}

